#### **IMPORTANDO LIBRERÍA NUMPY**

In [8]:
import numpy as np

##### Creando una lista de 10 Elementos

In [9]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### Transformando la Lista a un Array

In [10]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Corroborando el tipo de estructura


In [11]:
type(arreglo)

numpy.ndarray

##### Corroborando el tipo de datos del arreglo


In [12]:
arreglo.dtype

dtype('int64')

##### Definiendo el Array de int32 a float32


In [13]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### Sigue siendo un array de int32


In [14]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Transformando los datos de int32 a float32


In [15]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### También existe una función similar a Range pero ocupando Arrays

In [16]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Arreglo de 2 en 2 utilizando Arange

In [17]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

<h4 style = "color:lightblue"><b>ALGUNAS FUNCIONES DE NUMPY</b></h4>
<h4 style = "color:aquamarine">Obteniendo el promedio del array</h3>


In [18]:
promedio = np.mean(arreglo)
promedio

np.float64(5.5)

<h4 style = "color:aquamarine">Obteniendo la mediana del array</h4>


In [19]:
mediana = np.median(arreglo)
mediana

np.float64(5.5)

<h4 style = "color:aquamarine"> Desviación Estandar del Arreglo </h4>


In [20]:
desviacion_std = np.std(arreglo)
desviacion_std

np.float64(2.8722813232690143)

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo unos </h4>

In [21]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo ceros </h4>

In [22]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

<h4 style = "color:aquamarine"> Transformando el arreglo de unos de punto flotante a enteros </h4>


In [23]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h3 style = "color:orange"> <b>UTILIZANDO LA FUNCIÓN RANDOM</b> </h4>
<h4 style = "color:yellow"> Generando arreglo aleatorio de 5 elementos de Número entre 0 y 1</h4>



In [24]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio 

array([0.1815512 , 0.8134294 , 0.92916783, 0.83483542, 0.88755134,
       0.17239443, 0.25066741, 0.40632458, 0.2018721 , 0.92881041])

<h4 style = "color:yellow"> Generando una matriz aleatoria de 3x3</h4>


In [25]:
matriz = np.random.rand(3,3)
matriz

array([[0.52314409, 0.03648936, 0.68756553],
       [0.67572881, 0.30840668, 0.76619326],
       [0.76669589, 0.03516652, 0.28144064]])

<h4 style = "color:yellow"> Generando un arreglo aleatorio de 10 números enteros del 1 al 5</h4>


In [26]:
arreglo_aleatorio2  = np.random.randint(1,1001,10)
arreglo_aleatorio2

array([582, 798, 143, 262, 544, 457, 952, 228,  93, 997], dtype=int32)

<h4 style = "color:yellow"> Generando una matriz aleatoria de 10 números enteros del 1 al 100</h4>


In [27]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[ 20, 100,  63,  81,  29,  70,  28,   3,  51,  53],
       [ 52,  38,  49,   6,  98,  15,  77,   8,  67,  65],
       [  9,  37,  94,  65,  72,  65,  77,  71,  83,  45],
       [ 54,   6,  15,  17,  20,  91,  29,  59,  10,   7],
       [ 66,  32,  97,  32,  30,  80,  51,  24,  43,  19],
       [ 54,  45,  94,  82,  11,  23,  48,  56,  12,  99],
       [ 62,  94,   2,  86,  31,  40,   2,  54,  64,  64],
       [ 13,   9,  96,  74,  38,   6,  25,   1,  81,  85],
       [ 92,  25,  55,  11,  23,  99,  72,  17,  26,  72],
       [ 97,  41,  75,  23,  88,  82,  69,  13,  15,  21]], dtype=int32)